# An environment to develop, build, test, and document nbgitpuller-link
name: link
channels:
  - conda-forge
dependencies:
  - python =3
  - pip
  - click
  - validators
  - black
  - flake8
  - isort
  - nox
  - build
  - twine
  - pytest
  - pytest-cov
  - pytest-datadir
  - coveralls
  - zest.releaser
